# Generated by Django 3.2.6 on 2021-09-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('university_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('finishing_school_attended', models.CharField(choices=[('Yes', 'Y'), ('No', 'N'), ('NA', 'null')], default='NA', max_length=5)),
                ('placed_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_placed', models.CharField(max_length=255)),
                ('offer_mode', models.CharField(choices=[('On Campus', 'OC'), ('Off Campus', 'OFFC')], default='On Campus', max_length=20)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateOfInterview', models.CharField(max_length=255)),
                ('receivedOfferLetter', models.BooleanField()),
                ('dateOfOfferLetter', models.CharField(max_length=255)),
                ('recruit_year', models.CharField(max_length=5)),
                ('university_serial_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PMS_website.student_details')),
            ],
        ),
    ]
