# Generated by Django 3.2.6 on 2021-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='receivedOfferLetter',
            field=models.CharField(max_length=255),
        ),
    ]
