# Generated by Django 3.2.6 on 2021-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0002_alter_company_details_receivedofferletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='dateOfOfferLetter',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
