# Generated by Django 3.2.6 on 2021-09-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0003_alter_company_details_dateofofferletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='offer_mode',
            field=models.CharField(choices=[('OC', 'On Campus'), ('OFFC', 'Off Campus')], default='On Campus', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='finishing_school_attended',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('null', 'NA')], default='NA', max_length=5),
        ),
    ]
