# Generated by Django 3.2.6 on 2021-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0004_auto_20210910_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='company_type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT')], default='IT', max_length=255),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='offer_mode',
            field=models.CharField(choices=[('On Campus', 'On Campus'), ('Off Campus', 'Off Campus')], default='On Campus', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='finishing_school_attended',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='NA', max_length=5),
        ),
    ]
