# Generated by Django 3.2.6 on 2021-09-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0005_auto_20210917_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('AI&DS', 'AI & DS')], default='COMP', max_length=255)),
                ('summary_year', models.CharField(max_length=4)),
                ('total_students', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='company_details',
            name='receivedOfferLetter',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='department',
            field=models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('AI&DS', 'AI & DS')], default='COMP', max_length=255),
        ),
    ]
