# Generated by Django 3.2.6 on 2021-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0006_auto_20210927_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_detail',
            name='eligible_students',
            field=models.IntegerField(default=0),
        ),
    ]
