# Generated by Django 3.2.6 on 2022-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0009_higher_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrepreneurship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('COMP', 'COMP'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('AI&DS', 'AI & DS')], default='COMP', max_length=255)),
                ('entrepreneurship_year', models.CharField(max_length=4)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('student_names', models.TextField()),
                ('registration_number', models.CharField(blank=True, default='', max_length=1000)),
                ('start_date', models.CharField(blank=True, default='', max_length=100)),
                ('company_email', models.EmailField(blank=True, default='NA', max_length=254)),
                ('company_website', models.CharField(blank=True, default='NA', max_length=255)),
                ('company_mobile', models.CharField(blank=True, default='NA', max_length=10)),
                ('founder_name', models.CharField(blank=True, default='NA', max_length=255)),
                ('organisation_type', models.CharField(blank=True, default='NA', max_length=255)),
                ('incubation_year', models.CharField(blank=True, default='NA', max_length=4)),
                ('company_logo', models.ImageField(blank=True, upload_to='')),
                ('team_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
