# Generated by Django 3.2.6 on 2022-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_website', '0011_auto_20220128_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurship',
            name='company_email',
            field=models.CharField(blank=True, default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrepreneurship',
            name='registration_number',
            field=models.CharField(blank=True, default='NA', max_length=1000),
        ),
        migrations.AlterField(
            model_name='entrepreneurship',
            name='start_date',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
